apiVersion: manifests.package-operator.run/v1alpha1
kind: PackageManifest
metadata:
  name: kafka
spec:
  scopes:
  - Namespaced
  phases:
  - name: kafka
  availabilityProbes:
  - probes:
    - condition:
        type: Ready
        status: "True"
    selector:
      kind:
        group: kafka.strimzi.io
        kind: Kafka
