apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  annotations:
    package-operator.run/phase: infinispan
  name: infinispan
spec:
  replicas: 1
  security:
    endpointAuthentication: true
    endpointEncryption:
      type: None
    endpointSecretName: infinispan-identities
