apiVersion: v1
data:
  identities.yaml: Y3JlZGVudGlhbHM6Ci0gdXNlcm5hbWU6IGRldmVsb3BlcgogIHBhc3N3b3JkOiAwOWFpZGZrNG1yMzA5cnVzCg==
kind: Secret
metadata:
  annotations:
    package-operator.run/phase: infinispan
  name: infinispan-identities
---
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  annotations:
    package-operator.run/phase: infinispan
  name: infinispan
spec:
  replicas: 1
  security:
    endpointAuthentication: true
    endpointEncryption:
      type: None
    endpointSecretName: infinispan-identities
