apiVersion: manifests.package-operator.run/v1alpha1
kind: PackageManifest
metadata:
  name: application
spec:
  scopes:
  - Namespaced
  phases:
  - name: application
  availabilityProbes:
  - probes:
    - condition:
        type: Available
        status: "True"
    - fieldsEqual:
        fieldA: .status.updatedReplicas
        fieldB: .status.replicas
    selector:
      kind:
        group: apps
        kind: Deployment
  config:
    openAPIV3Schema:
      type: object
      properties:
        adminPassword:
          type: string
          description: "Hashed dashboard password for admin user"
          default: 27e39ea189b5f9dc88ed0e73c86750191fa65049
